import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';
import Admin from '../models/Admin.js';
import Product from '../models/Product.js';
import Offer from '../models/Offer.js';
import Enquiry from '../models/Enquiry.js';
import Testimonial from '../models/Testimonial.js';

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/mykouch';

const seedProducts = [
  // 1. L-Shaped Sofas
  {
    name: 'myKouch Royal Emerald Velvet L-Shape Sectional',
    slug: 'mykouch-royal-emerald-velvet-l-shape',
    description: 'A masterpiece of contemporary luxury. Upholstered in jewel-tone emerald green royal velvet with geometric diamond tufting, bow-tie accent buttons, and champagne gold electroplated metal legs. Features deep ergonomic seats with 40-density high-resilience memory foam for cloud-like comfort.',
    category: 'L-Shaped Sofas',
    images: [
      '/assets/sofas/drawing_room_1_2.jpg',
      '/assets/sofas/drawing_room_1_12.jpg',
      '/assets/sofas/drawing_room_1_10.jpg',
    ],
    price: 54999,
    originalPrice: 78999,
    discount: 30,
    dimensions: '108" L x 72" W x 34" H (Customizable to your room)',
    seatingCapacity: '6 - 7 Seater',
    colors: ['Emerald Teal', 'Royal Navy', 'Warm Terracotta', 'Ivory Beige', 'Charcoal Grey'],
    materials: ['Royal Velvet', 'Stain-Resistant Chenille', 'Bouclé'],
    badge: 'Bestseller',
    isNewArrival: false,
    isTopSelling: true,
    rating: 4.9,
    reviewsCount: 38,
    specifications: {
      frameMaterial: 'Termite-Proof Treated Sal & Marandi Hardwood Frame',
      foamDensity: '40 Density High Resilience (HR) Supersoft Foam with Memory Layer',
      suspension: 'Heavy-Gauge Carbon Zig-Zag Springs & Reinforced Poly-Webbing',
      warranty: '10 Years Frame & Structural Warranty',
      legs: 'Solid Metal Legs with Electroplated Champagne Gold Finish',
      customizable: true,
    },
  },
  {
    name: 'myKouch Tuscany Quilted L-Shaped Corner Sofa',
    slug: 'mykouch-tuscany-quilted-l-shaped-corner-sofa',
    description: 'Designed for spacious open-concept living rooms. Features tailored diamond-stitched lumbar cushions, curved armrests, and dual-tone upholstery combining premium beige suede with espresso brown leatherette trims.',
    category: 'L-Shaped Sofas',
    images: [
      '/assets/sofas/drawing_room_1_12.jpg',
      '/assets/sofas/drawing_room_1_11.jpg',
      '/assets/sofas/drawing_room_1_15.jpg',
    ],
    price: 49999,
    originalPrice: 69999,
    discount: 28,
    dimensions: '102" L x 68" W x 35" H',
    seatingCapacity: '5 - 6 Seater',
    colors: ['Beige & Espresso', 'Charcoal & Grey', 'Olive & Walnut', 'Desert Sand'],
    materials: ['Textured Suede', 'Breathable Leatherette', 'Polyester Velvet'],
    badge: 'Trending',
    isNewArrival: false,
    isTopSelling: true,
    rating: 4.8,
    reviewsCount: 29,
    specifications: {
      frameMaterial: 'Seasoned Solid Hardwood with Anti-Borer Treatment',
      foamDensity: '38 Density High Density Rebound Foam',
      suspension: 'High-Tensile S-Springs & 3-Inch Elastic Webbing',
      warranty: '10 Years Manufacturer Warranty',
      legs: 'Brushed Golden Alloy Base Caps',
      customizable: true,
    },
  },
  {
    name: 'myKouch Celestia Sky Blue Sectional with Ottoman',
    slug: 'mykouch-celestia-sky-blue-sectional',
    description: 'Elevate your living space with the Celestia sectional in soothing sky blue ribbed velvet. Comes with a matching oversized center ottoman with tufted top and built-in storage capabilities upon request.',
    category: 'L-Shaped Sofas',
    images: [
      '/assets/sofas/drawing_room_1_10.jpg',
      '/assets/sofas/drawing_room_1_13.jpg',
    ],
    price: 58999,
    originalPrice: 84999,
    discount: 30,
    dimensions: '112" L x 76" W x 33" H',
    seatingCapacity: '7 Seater',
    colors: ['Sky Blue', 'Mint Green', 'Cream White', 'Dove Grey'],
    materials: ['Ribbed Plush Velvet', 'Performance Chenille'],
    badge: 'Luxury Edition',
    isNewArrival: true,
    isTopSelling: true,
    rating: 5.0,
    reviewsCount: 16,
    specifications: {
      frameMaterial: 'Kiln-Dried Solid Pine & Hardwood Reinforcements',
      foamDensity: '42 Density High Resilient Foam with Feather Blend Topper',
      suspension: 'German Engineered Pocket Springs Matrix',
      warranty: '10 Years Frame Warranty',
      legs: 'Concealed Heavy-Duty Low Profile Wood Feet',
      customizable: true,
    },
  },
  {
    name: 'myKouch Aurelia Rose Velvet Corner Lounger',
    slug: 'mykouch-aurelia-rose-velvet-corner-lounger',
    description: 'Sophisticated dusty rose velvet sectional with handcrafted Chesterfield deep button tufting along the side arms and ottoman. Perfectly suited for contemporary apartments craving a romantic aesthetic.',
    category: 'L-Shaped Sofas',
    images: [
      '/assets/sofas/drawing_room_1_11.jpg',
      '/assets/sofas/drawing_room_1_14.jpg',
    ],
    price: 52999,
    originalPrice: 74999,
    discount: 29,
    dimensions: '98" L x 66" W x 34" H',
    seatingCapacity: '5 Seater',
    colors: ['Dusty Rose', 'Champagne Beige', 'Lavender Mist', 'Warm Ochre'],
    materials: ['Silk Velvet', 'Italian Bouclé'],
    badge: 'Popular',
    isNewArrival: false,
    isTopSelling: false,
    rating: 4.8,
    reviewsCount: 21,
    specifications: {
      frameMaterial: 'Solid Sal Wood Structure with Corner Blocks',
      foamDensity: '35 Density Memory Infused Foam',
      suspension: 'Zig-zag Springs with Sound Dampeners',
      warranty: '10 Years Frame Warranty',
      legs: 'Tapered Brass Plated Steel Legs',
      customizable: true,
    },
  },

  // 2. Sofa Combos (3+1+1 and Suites)
  {
    name: 'myKouch Imperial Fluted 3+1+1 Living Room Suite',
    slug: 'mykouch-imperial-fluted-311-suite',
    description: 'The epitome of classic Indian luxury. A complete 5-seater sofa suite comprising a stately 3-seater linear sofa and two royal single lounge chairs. Features vertical channel fluting in pristine ivory white fabric with golden leaf accents on the armrest profiles.',
    category: 'Sofa Combos',
    images: [
      '/assets/sofas/drawing_room_1_16.jpg',
      '/assets/sofas/drawing_room_1_1.jpg',
      '/assets/sofas/drawing_room_1_18.jpg',
    ],
    price: 68999,
    originalPrice: 99999,
    discount: 31,
    dimensions: '3-Seater: 84" L x 36" D x 34" H | 1-Seater (x2): 38" L x 36" D x 34" H',
    seatingCapacity: '5 Seater (3 + 1 + 1)',
    colors: ['Pristine Ivory', 'Royal Maroon', 'Charcoal Slate', 'Emerald Gold'],
    materials: ['Fluted Microfiber Fabric', 'Italian Leatherette', 'Velvet'],
    badge: 'Showroom Pick',
    isNewArrival: false,
    isTopSelling: true,
    rating: 4.9,
    reviewsCount: 42,
    specifications: {
      frameMaterial: 'Solid Sal Hardwood with Moisture & Borer Resistance',
      foamDensity: '40 Density HR Foam + Supersoft Cloud Layer',
      suspension: 'Interwoven Webbing & Carbon Steel Springs',
      warranty: '10 Years Frame Warranty',
      legs: 'Custom Gold Tipped Wooden Stumps',
      customizable: true,
    },
  },
  {
    name: 'myKouch Bordeaux Vintage 3+1+1 Leatherette Set',
    slug: 'mykouch-bordeaux-vintage-leatherette-set',
    description: 'Stately deep burgundy maroon leatherette suite with diamond button tufting and sculpted wooden arm caps. Offers unmatched durability, effortless wipe-clean maintenance, and grand heritage aesthetics.',
    category: 'Sofa Combos',
    images: [
      '/assets/sofas/drawing_room_1_1.jpg',
      '/assets/sofas/drawing_room_1_17.jpg',
    ],
    price: 62999,
    originalPrice: 89999,
    discount: 30,
    dimensions: '3-Seater: 82" L x 35" D | 1-Seater: 36" L x 35" D',
    seatingCapacity: '5 Seater (3 + 1 + 1)',
    colors: ['Bordeaux Maroon', 'Espresso Brown', 'Cognac Tan', 'Jet Black'],
    materials: ['Automotive-Grade Breathable Leatherette', 'Solid Wood Accents'],
    badge: 'Heritage',
    isNewArrival: false,
    isTopSelling: true,
    rating: 4.7,
    reviewsCount: 31,
    specifications: {
      frameMaterial: 'Heavy Seasoned Hardwood Framework',
      foamDensity: '40 Density Heavy Duty Foam',
      suspension: 'Steel Wire Grid & Carbon Springs',
      warranty: '10 Years Frame Warranty',
      legs: 'Carved Hardwood Feet in Walnut Polish',
      customizable: true,
    },
  },
  {
    name: 'myKouch Dual-Tone Cyan 3+1+1 Contemporary Set',
    slug: 'mykouch-dual-tone-cyan-311-set',
    description: 'Dynamic two-tone styling featuring striking cyan blue and graphite grey panels. Built with wide track arms, integrated cushion bolsters, and ergonomic lower back support for everyday family relaxation.',
    category: 'Sofa Combos',
    images: [
      '/assets/sofas/drawing_room_1_18.jpg',
      '/assets/sofas/drawing_room_1_3.jpg',
    ],
    price: 54999,
    originalPrice: 76999,
    discount: 28,
    dimensions: '3-Seater: 80" L x 34" D | 1-Seater: 35" L x 34" D',
    seatingCapacity: '5 Seater (3 + 1 + 1)',
    colors: ['Cyan & Graphite', 'Mustard & Charcoal', 'Rust & Ivory', 'Teal & Grey'],
    materials: ['High GSM Textured Suede', 'Spill-Resistant Fabric'],
    badge: 'Family Favorite',
    isNewArrival: false,
    isTopSelling: false,
    rating: 4.8,
    reviewsCount: 19,
    specifications: {
      frameMaterial: 'Sal Wood Main Framework with Plywood Reinforcements',
      foamDensity: '36 Density Resilient Foam',
      suspension: 'Elastic Webbing with Silent Springs',
      warranty: '10 Years Frame Warranty',
      legs: 'Square Solid Polymer / Wood Blocks',
      customizable: true,
    },
  },

  // 3. 3-Seater Sofas
  {
    name: 'myKouch Versailles Fluted 3-Seater Linear Sofa',
    slug: 'mykouch-versailles-fluted-3-seater',
    description: 'Clean lines meet timeless architectural fluting. The Versailles 3-seater provides generous seating for three adults with continuous channel backrests, curved shelter arms, and premium brass feet.',
    category: '3 Seater Sofas',
    images: [
      '/assets/sofas/drawing_room_1_20.jpg',
      '/assets/sofas/drawing_room_1_4.jpg',
    ],
    price: 38999,
    originalPrice: 54999,
    discount: 29,
    dimensions: '84" L x 36" D x 34" H',
    seatingCapacity: '3 Seater',
    colors: ['Ivory Cream', 'Sage Green', 'Terracotta Orange', 'Midnight Blue'],
    materials: ['Ultra-Soft Fluted Velvet', 'Belgian Linen Blend'],
    badge: 'Bestseller',
    isNewArrival: false,
    isTopSelling: true,
    rating: 4.9,
    reviewsCount: 35,
    specifications: {
      frameMaterial: 'Treated Sal Hardwood',
      foamDensity: '40 Density High Resilience Foam',
      suspension: 'Zig-zag Springs & Webbing',
      warranty: '10 Years Frame Warranty',
      legs: 'Brushed Golden Metal Legs',
      customizable: true,
    },
  },
  {
    name: 'myKouch Nordic Minimalist 3-Seater Sofa',
    slug: 'mykouch-nordic-minimalist-3-seater',
    description: 'Scandinavian-inspired linear sofa with clean boxy cushions, generous seat depth, and tactile bouclé upholstery that brings warmth and Scandinavian tranquility into modern homes.',
    category: '3 Seater Sofas',
    images: [
      '/assets/sofas/drawing_room_1_21.jpg',
      '/assets/sofas/drawing_room_1_22.jpg',
    ],
    price: 34999,
    originalPrice: 48999,
    discount: 28,
    dimensions: '78" L x 35" D x 33" H',
    seatingCapacity: '3 Seater',
    colors: ['Oatmeal Bouclé', 'Sand Tan', 'Slate Grey', 'Olive Moss'],
    materials: ['Heavy Textured Bouclé', 'Premium Chenille'],
    badge: 'New Arrival',
    isNewArrival: true,
    isTopSelling: false,
    rating: 4.8,
    reviewsCount: 14,
    specifications: {
      frameMaterial: 'Kiln-Dried Hardwood Frame',
      foamDensity: '35 Density Memory-Enhanced Foam',
      suspension: 'Heavy Gauge Elastic Webbing',
      warranty: '10 Years Frame Warranty',
      legs: 'Natural Tapered Oak Legs',
      customizable: true,
    },
  },
  {
    name: 'myKouch Chesterfield Royal Velvet 3-Seater',
    slug: 'mykouch-chesterfield-royal-velvet-3-seater',
    description: 'Timeless British craftsmanship tailored for modern spaces. Deep hand-buttoned diamond tufts across the rolled back and arms with individually applied upholstery studs.',
    category: '3 Seater Sofas',
    images: [
      '/assets/sofas/drawing_room_1_23.jpg',
      '/assets/sofas/drawing_room_1_24.jpg',
    ],
    price: 42999,
    originalPrice: 59999,
    discount: 28,
    dimensions: '88" L x 38" D x 32" H',
    seatingCapacity: '3 Seater',
    colors: ['Forest Green', 'Royal Navy Blue', 'Rich Cognac', 'Charcoal'],
    materials: ['Silk Velvet', 'Vintage Distressed Leatherette'],
    badge: 'Classic Choice',
    isNewArrival: false,
    isTopSelling: true,
    rating: 4.9,
    reviewsCount: 27,
    specifications: {
      frameMaterial: 'Solid Sal Wood Framework',
      foamDensity: '40 Density High Resilience Foam',
      suspension: 'Heavy Gauge Hand-Tied Coil System',
      warranty: '10 Years Frame Warranty',
      legs: 'Turned Solid Wooden Legs with Brass Castors',
      customizable: true,
    },
  },

  // 4. Recliner Sofas
  {
    name: 'myKouch CloudMotion Motorized Luxury Recliner',
    slug: 'mykouch-cloudmotion-motorized-luxury-recliner',
    description: 'Experience zero-gravity relaxation with silent motorized footrest extension and infinite-position recline. Features built-in USB-C fast charging port, soft lumbar air cushions, and breathable Napa leatherette.',
    category: 'Recliner Sofas',
    images: [
      '/assets/sofas/drawing_room_1_25.jpg',
      '/assets/sofas/drawing_room_1_26.jpg',
    ],
    price: 36999,
    originalPrice: 52999,
    discount: 30,
    dimensions: '38" W x 40" D x 42" H (Fully reclined: 66" D)',
    seatingCapacity: 'Single Recliner',
    colors: ['Espresso Brown', 'Cognac Tan', 'Charcoal Slate', 'Bone Cream'],
    materials: ['Napa-Grade Breathable Leatherette', 'High Performance Suede'],
    badge: 'Bestseller',
    isNewArrival: false,
    isTopSelling: true,
    rating: 5.0,
    reviewsCount: 46,
    specifications: {
      frameMaterial: 'Heavy Duty Steel Mechanism & Hardwood Enclosure',
      foamDensity: '45 Density Molded Ergonomic Polyurethane Foam',
      suspension: 'German OKIN Motor & Dual Tension Springs',
      warranty: '10 Years Frame & 3 Years Motor Warranty',
      legs: 'Heavy-Duty 360-Degree Swivel Base',
      customizable: true,
    },
  },
  {
    name: 'myKouch Grand Cinema 3-Seater Dual Motor Recliner',
    slug: 'mykouch-grand-cinema-3-seater-dual-motor-recliner',
    description: 'Bring the private cinema experience to your living room. A 3-seater powerhouse where both outer seats independently recline at the touch of a button. Features drop-down center console with dual stainless cup holders and concealed storage.',
    category: 'Recliner Sofas',
    images: [
      '/assets/sofas/drawing_room_1_27.jpg',
      '/assets/sofas/drawing_room_1_28.jpg',
    ],
    price: 74999,
    originalPrice: 104999,
    discount: 28,
    dimensions: '86" L x 40" D x 42" H',
    seatingCapacity: '3 Seater Recliner',
    colors: ['Midnight Black', 'Chocolate Brown', 'Smoke Grey'],
    materials: ['Heavy-Duty Bonded Leatherette', 'Stain-Resistant Microfiber'],
    badge: 'Home Cinema',
    isNewArrival: true,
    isTopSelling: true,
    rating: 4.9,
    reviewsCount: 22,
    specifications: {
      frameMaterial: 'Industrial Steel Frame Structure',
      foamDensity: '42 Density High Resilience Molded Foam',
      suspension: 'Twin Heavy-Duty German Actuator Motors',
      warranty: '10 Years Frame & 3 Years Mechanism Warranty',
      legs: 'Anti-Skid Steel Anchors',
      customizable: true,
    },
  },

  // 5. 2-Seater Sofas / Loveseats
  {
    name: 'myKouch Haven Compact Velvet Loveseat',
    slug: 'mykouch-haven-compact-velvet-loveseat',
    description: 'Designed specifically for modern apartments, bedrooms, and cozy conversation nooks. Deep seating with slim track arms to maximize sitting area without consuming floor space.',
    category: '2 Seater Sofas',
    images: [
      '/assets/sofas/drawing_room_1_29.jpg',
      '/assets/sofas/drawing_room_1_30.jpg',
    ],
    price: 26999,
    originalPrice: 37999,
    discount: 28,
    dimensions: '60" L x 34" D x 33" H',
    seatingCapacity: '2 Seater',
    colors: ['Terracotta', 'Emerald', 'Mustard Gold', 'Steel Grey'],
    materials: ['Royal Velvet', 'Bouclé Weave'],
    badge: 'Apartment Pick',
    isNewArrival: false,
    isTopSelling: false,
    rating: 4.8,
    reviewsCount: 18,
    specifications: {
      frameMaterial: 'Solid Sal Wood Framework',
      foamDensity: '38 Density HR Foam',
      suspension: 'High Tensile Webbing & Springs',
      warranty: '10 Years Frame Warranty',
      legs: 'Champagne Gold Plated Metal Legs',
      customizable: true,
    },
  },
  {
    name: 'myKouch Cozy Petite 2-Seater Studio Sofa',
    slug: 'mykouch-cozy-petite-2-seater-studio-sofa',
    description: 'A cozy sanctuary for compact spaces. Soft rounded corners, cloud-soft backrest bolsters, and breathable linen-feel upholstery.',
    category: '2 Seater Sofas',
    images: [
      '/assets/sofas/drawing_room_1_31.jpg',
      '/assets/sofas/drawing_room_1_32.jpg',
    ],
    price: 24999,
    originalPrice: 34999,
    discount: 28,
    dimensions: '56" L x 33" D x 32" H',
    seatingCapacity: '2 Seater',
    colors: ['Ivory Cream', 'Sage Green', 'Warm Rust', 'Charcoal'],
    materials: ['Textured Linen-Cotton Blend', 'Soft Suede'],
    badge: 'New Arrival',
    isNewArrival: true,
    isTopSelling: false,
    rating: 4.7,
    reviewsCount: 12,
    specifications: {
      frameMaterial: 'Seasoned Hardwood Frame',
      foamDensity: '35 Density Soft Foam',
      suspension: 'Elastic Webbing Support',
      warranty: '10 Years Frame Warranty',
      legs: 'Natural Finish Solid Wood Tapered Legs',
      customizable: true,
    },
  },

  // 6. Mattress & Beddings
  {
    name: 'myKouch Imperial Orthopedic Euro-Top Pocket Spring Hybrid Mattress',
    slug: 'mykouch-imperial-orthopedic-euro-top-pocket-spring-mattress',
    description:
      'Flagship orthopedic hybrid sleep system engineered for perfect spinal alignment and zero-motion disturbance. Combines individually encased carbon steel pocket coils with a deep Euro-top comfort cushion, breathable geometric knit jacquard ticking, and fluted charcoal sidewalls with ergonomic transport handles.',
    category: 'Mattress & Beddings',
    subType: 'pocket-spring',
    images: [
      '/assets/mattresses/imperial_orthopedic_euro_top_pocket_spring_mattress.jpg',
      '/assets/mattresses/pocket_spring_hybrid_hero.jpg',
      '/assets/mattresses/pocket_spring_macro_quilt.jpg',
      '/assets/mattresses/pocket_spring_edge_support.jpg',
      '/assets/mattresses/pocket_spring_cross_section.jpg',
    ],
    price: 34999,
    originalPrice: 49999,
    discount: 30,
    dimensions: '78" L x 72" W x 10" Thick',
    seatingCapacity: 'King Size (78" x 72")',
    colors: ['White Jacquard & Charcoal Fluted Border', 'Slate Grey Accent'],
    materials: [
      'Individually Encased High-Tensile Pocket Coils',
      'Cool-Gel Visco Elastic Memory Foam',
      'High-Density Edge Support Foam Casing',
      'Breathable Chevron Jacquard Ticking',
    ],
    badge: 'Doctor Recommended',
    isNewArrival: true,
    isTopSelling: true,
    rating: 5.0,
    reviewsCount: 52,
    specifications: {
      frameMaterial: 'Individually Encased Pocket Spring Chassis with High-Density Perimeter Foam Enclosure',
      foamDensity: '50-Density Visco Elastic Memory Foam + 40D HR Transition Layer',
      suspension: 'Multi-Zone Independent Carbon Steel Pocket Spring Coils (Zero Motion Transfer)',
      warranty: '10 Years Direct Manufacturer Warranty with Zero-Sag Guarantee',
      legs: 'Anti-Skid Bottom Fabric',
      customizable: true,
    },
  },
  {
    name: 'myKouch CloudHaven Baffle-Box Pillow-Top Mattress Topper',
    slug: 'mykouch-cloudhaven-baffle-box-pillow-top-mattress-topper',
    description:
      'Transform any mattress into a 5-star luxury hotel cloud bed. Engineered with a 3-inch high-loft down-alternative microfiber fill enclosed in 300-thread-count breathable cotton percale. Features square baffle-box stitching to prevent filling displacement, and heavy-duty 4-corner elastic anchor bands for a secure, non-slip fit.',
    category: 'Mattress & Beddings',
    subType: 'toppers',
    images: [
      '/assets/beddings/hotel_cloud_baffle_box_mattress_topper.jpg',
    ],
    price: 4999,
    originalPrice: 7499,
    discount: 33,
    dimensions: '78" L x 72" W x 3" Thick (King Size)',
    seatingCapacity: 'King Size (78" x 72")',
    colors: ['Crisp Cloud White', 'Ivory Pearl'],
    materials: [
      '300 TC Breathable Cotton Percale Shell',
      '7D Virgin Down-Alternative Microfiber Fill',
      'Heavy-Duty Elastic Corner Anchors',
    ],
    badge: 'Hotel Cloud Comfort',
    isNewArrival: true,
    isTopSelling: true,
    rating: 4.9,
    reviewsCount: 42,
    specifications: {
      frameMaterial: 'Baffle-Box Grid Quilted Construction with Double-Needle Piped Borders',
      foamDensity: '1200 GSM Virgin Down-Alternative Microfiber Loft Layer',
      suspension: '4-Corner Heavy-Duty Elastic Anchor Bands',
      warranty: '3 Years Anti-Clump & Loft Retention Guarantee',
      legs: 'Elastic Corner Straps',
      customizable: true,
    },
  },
  {
    name: 'myKouch Diamond-Quilted 100% Waterproof Fitted Mattress Protector',
    slug: 'mykouch-diamond-quilted-waterproof-fitted-mattress-protector',
    description:
      'Ultimate all-night protection against liquids, spills, sweat, allergens, and dust mites. Features a completely silent, breathable TPU waterproof membrane beneath a plush diamond-quilted microfiber comfort surface. Deep 360-degree all-around stretchable skirt hugs mattresses up to 15 inches thick with zero wrinkles or rustling noise.',
    category: 'Mattress & Beddings',
    subType: 'toppers',
    images: [
      '/assets/beddings/diamond_quilted_waterproof_mattress_protector.jpg',
    ],
    price: 2499,
    originalPrice: 3999,
    discount: 37,
    dimensions: '78" L x 72" W x 15" Deep Skirt',
    seatingCapacity: 'King Size (78" x 72")',
    colors: ['Pure White', 'Warm Ivory'],
    materials: [
      'Diamond-Quilted Hypoallergenic Microfiber',
      'Silent Breathable TPU Waterproof Membrane',
      '360° All-Around Stretchable Poly-Elastane Skirt',
    ],
    badge: '100% Waterproof',
    isNewArrival: true,
    isTopSelling: true,
    rating: 5.0,
    reviewsCount: 58,
    specifications: {
      frameMaterial: '360-Degree Deep Pocket Fitted Skirt with Heavy-Duty Elastic Band',
      foamDensity: 'Hypoallergenic Microfiber Cushioning with Thermoplastic Polyurethane Membrane',
      suspension: 'Silent Noise-Free Waterproof Lamination',
      warranty: '5 Years Waterproof Membrane Warranty',
      legs: 'Full Elastic Skirt',
      customizable: true,
    },
  },
  {
    name: 'myKouch ZenComfort Japanese Foldable Futon Floor Mattress & Bedding Topper',
    slug: 'mykouch-zencomfort-foldable-futon-floor-mattress-topper',
    description:
      'Multi-purpose Japanese-style roll-up futon mattress and supportive sleeping floor pad. Crafted with high-density pressure-relieving core wrapped in soft brushed microfiber with square channel tufting. Equipped with reinforced corner straps for mattress overlay or convenient roll-and-store portability for floor sleeping, guest bedding, and meditation.',
    category: 'Mattress & Beddings',
    subType: 'beddings',
    images: [
      '/assets/beddings/zencomfort_foldable_futon_floor_mattress_topper.jpg',
    ],
    price: 5499,
    originalPrice: 8499,
    discount: 35,
    dimensions: '78" L x 60" W x 4" Thick (Queen Size)',
    seatingCapacity: 'Queen Size (78" x 60")',
    colors: ['Slate Grey', 'Charcoal Heather', 'Oatmeal Beige'],
    materials: [
      'Brushed Micro-Peach Fabric Casing',
      'High-Density Aerodynamic Cushion Core',
      'Reinforced Roll-Up Elastic Straps',
    ],
    badge: 'Foldable Futon',
    isNewArrival: true,
    isTopSelling: false,
    rating: 4.8,
    reviewsCount: 34,
    specifications: {
      frameMaterial: 'Roll-Up & Foldable Portable Design with Heavy-Duty Corner Elastic Bands',
      foamDensity: 'Dual-Layer Ergonomic Cushion Core with Micro-Peach Surface',
      suspension: 'Multi-Layer Resilient Core with Square Channel Tufting',
      warranty: '5 Years Sag-Free Core Warranty',
      legs: 'Floor & Mattress Overlay Bands',
      customizable: true,
    },
  },
  {
    name: 'myKouch Celestial Wave-Quilted Euro-Pillowtop Cooling Mattress Topper',
    slug: 'mykouch-celestial-wave-quilted-euro-pillowtop-cooling-topper',
    description:
      'Ultra-thick hotel-grade cooling Euro-top mattress topper. Tailored with distinctive deep wave baffle quilting and signature midnight navy piped borders. Infused with cooling hollow conjugate fibers that promote continuous airflow while cradling shoulders, hips, and lower back for zero-pressure restorative rest.',
    category: 'Mattress & Beddings',
    subType: 'toppers',
    images: [
      '/assets/beddings/royal_luxe_wave_quilted_euro_topper.jpg',
    ],
    price: 5999,
    originalPrice: 8999,
    discount: 33,
    dimensions: '78" L x 72" W x 4" Thick (King Size)',
    seatingCapacity: 'King Size (78" x 72")',
    colors: ['Cloud White & Midnight Navy Piping', 'Ivory Pearl & Slate Accent'],
    materials: [
      'Cooling Breathable Jacquard Ticking',
      'High-Loft 7D Hollow Conjugate Down-Alternative Fill',
      'Contrast Midnight Navy Piping',
    ],
    badge: 'Ultra-Plush Cooling',
    isNewArrival: true,
    isTopSelling: true,
    rating: 5.0,
    reviewsCount: 61,
    specifications: {
      frameMaterial: 'Deep Wave Baffle-Box Stitching with Dual-Edge Contrast Navy Piping',
      foamDensity: '1400 GSM Extra-Loft Cooling Hollow Fiber Filling',
      suspension: 'Deep Elastic Anchor Skirt for Secure Zero-Slip Hold',
      warranty: '3 Years Anti-Clump & Shape Retention Guarantee',
      legs: 'Deep Elastic Fitted Skirt',
      customizable: true,
    },
  },

  // 7. Pillow & Cushion
  {
    name: 'myKouch Royal Indigo Mediterranean Tile-Medallion & Damask Cushion Suite (Set of 4 + Navy Throw Blanket)',
    slug: 'mykouch-royal-indigo-mediterranean-tile-medallion-cushion-suite',
    description:
      'Bespoke coastal living luxury. A curated living room sofa styling suite featuring four coordinated artisanal cushions: a showstopping Portuguese tile-medallion floral motif pillow, an intricate palm-frond feather pattern cushion, and two deep royal indigo woven textured accent pillows, completed with an ultra-soft waffle-knit navy fringed throw blanket draped over the seat.',
    category: 'Pillow & Cushion',
    subType: 'throw-cushions',
    images: [
      '/assets/pillows/royal_indigo_mediterranean_cushion_suite.jpg',
      '/assets/pillows/designer_living_throw_cushions.jpg',
    ],
    price: 3899,
    originalPrice: 5999,
    discount: 35,
    dimensions: '18" x 18" (45 x 45 cm) [x4] + 50" x 60" Navy Fringed Knit Blanket',
    seatingCapacity: 'Suite of 4 Cushions + 1 Matching Fringed Navy Throw',
    colors: ['Royal Navy Blue', 'Indigo Slub Texture', 'Crisp White Medallion', 'Coastal Denim'],
    materials: [
      'Heavyweight Textured Slub Linen',
      'High-Definition Screen Printed Medallion Canvas',
      'Chunky Fringed Waffle Knit Throw',
      'Concealed YKK Brass Zippers',
    ],
    badge: 'Trending Mediterranean',
    isNewArrival: true,
    isTopSelling: true,
    rating: 5.0,
    reviewsCount: 42,
    specifications: {
      frameMaterial: 'Concealed Bottom YKK Zipper with Double-Interlocked Edge Piping',
      foamDensity: '100% Virgin Siliconized Micro-Down Alternative Fiber (700 GSM)',
      suspension: 'Reinforced Overlock Stress-Point Stitching',
      warranty: '2 Years Seam Burst & Fabric Colorfast Guarantee',
      legs: 'Hidden Bottom Zipper Placket',
      customizable: true,
    },
  },
  {
    name: 'myKouch Bohemian Artisanal Macramé & Tufted Tassel Cushion Ensemble (Set of 5 + Handwoven Fringed Throw)',
    slug: 'mykouch-bohemian-artisanal-macrame-tufted-tassel-cushion-ensemble',
    description:
      'Artisanal bohemian tactile mastery for sophisticated Scandinavian living spaces. Handcrafted ensemble featuring five unique textured ivory pillows: diamond lattice knotted macramé, 3D raised floral pom-pom tufts, linear textured loop embroidery, geometric chevron tufting with hand-tied corner tassels, and chunky bobble-stitch knit. Accented with an artisanal open-weave fringed sofa throw blanket.',
    category: 'Pillow & Cushion',
    subType: 'throw-cushions',
    images: [
      '/assets/pillows/bohemian_macrame_tufted_tassel_cushion_suite.jpg',
      '/assets/pillows/designer_living_throw_cushions.jpg',
    ],
    price: 4699,
    originalPrice: 6999,
    discount: 33,
    dimensions: '18" x 18" (45 x 45 cm) [x5] + 55" x 65" Open-Weave Fringe Throw Blanket',
    seatingCapacity: 'Set of 5 Handcrafted Cushions + 1 Handwoven Fringe Throw',
    colors: ['Natural Raw Ivory', 'Warm Ecru Cream', 'Textured Oatmeal Linen'],
    materials: [
      '100% Organic Raw Cotton Macramé Cord',
      'Textured Loop Tufting & Hand-Tied Tassels',
      'Heavy Slub Canvas Backing',
      'Concealed YKK Zippers',
    ],
    badge: 'Handcrafted Macramé',
    isNewArrival: true,
    isTopSelling: true,
    rating: 5.0,
    reviewsCount: 58,
    specifications: {
      frameMaterial: 'Hand-Knotted Macramé & 3D Tufted Cotton with Reinforced Edge Seams',
      foamDensity: 'Hypoallergenic Virgin Microfiber Cloud Insert (750 GSM)',
      suspension: 'Heavy-Duty Anti-Fray Backing Canvas with Concealed Zipper',
      warranty: '2 Years Macramé Knots & Fabric Integrity Guarantee',
      legs: 'Concealed Base Zipper Placket',
      customizable: true,
    },
  },
  {
    name: 'myKouch Tuscan Terracotta & Amber Sunburst Botanical Cushion Suite (Set of 4 + Ribbed Terracotta Throw)',
    slug: 'mykouch-tuscan-terracotta-amber-sunburst-botanical-cushion-suite',
    description:
      'Radiant autumn warmth and Italian architectural flair. Hand-tailored styling set featuring four statement cushions: an artistic abstract monstera-leaf botanical silhouette on ivory linen, an optical terracotta chevron stripe pillow, a quilted honeycomb velvet pillow in glowing amber ochre, and an arched sunburst linear embroidered cushion. Draped with a matching cozy ribbed fringed terracotta throw blanket.',
    category: 'Pillow & Cushion',
    subType: 'throw-cushions',
    images: [
      '/assets/pillows/tuscan_terracotta_amber_botanical_cushion_suite.jpg',
      '/assets/pillows/designer_living_throw_cushions.jpg',
    ],
    price: 4199,
    originalPrice: 6499,
    discount: 35,
    dimensions: '18" x 18" (45 x 45 cm) [x4] + 50" x 60" Ribbed Knit Throw Blanket',
    seatingCapacity: 'Suite of 4 Pillows + 1 Matching Fringed Terracotta Throw',
    colors: ['Tuscan Terracotta Rust', 'Amber Ochre Velvet', 'Warm Ivory Cream', 'Burnt Orange'],
    materials: [
      'High-Density Cotton Linen Slub',
      'Honeycomb Quilted Silk Velvet',
      'Ribbed Chenille Acrylic Throw',
      'Concealed YKK Zippers',
    ],
    badge: 'Autumn Harvest Pick',
    isNewArrival: true,
    isTopSelling: true,
    rating: 4.9,
    reviewsCount: 49,
    specifications: {
      frameMaterial: 'Precision Chain-Stitch Botanical Embroidery with Concealed Zipper Placket',
      foamDensity: 'High-Loft Virgin Conjugate Down Alternative (700 GSM)',
      suspension: 'Double-Interlocked Overlock Seams with Anti-Pilling Finish',
      warranty: '2 Years Embroidery & Fabric Colorfast Guarantee',
      legs: 'Hidden Bottom Zipper Placket',
      customizable: true,
    },
  },
  {
    name: 'myKouch Nordic Oatmeal & Autumn Harvest Linen Cushion Suite (Set of 4 + Handcrafted Pumpkin Accent & Fringed Throw)',
    slug: 'mykouch-nordic-oatmeal-harvest-linen-cushion-suite',
    description:
      'Tranquil Scandinavian warmth and textural living harmony. Styled in serene earth tones, this ensemble features four artisanal elements: a soft botanical trailing-leaf floral printed linen cushion, a crisp cream woven herringbone cushion, an earthen oatmeal chevron tweed pillow, a sculpted tweed pumpkin novelty bouclé accent cushion with wooden stem, and a lightweight ivory fringed sofa throw.',
    category: 'Pillow & Cushion',
    subType: 'throw-cushions',
    images: [
      '/assets/pillows/nordic_oatmeal_harvest_pumpkin_cushion_suite.jpg',
      '/assets/pillows/designer_living_throw_cushions.jpg',
    ],
    price: 3799,
    originalPrice: 5599,
    discount: 32,
    dimensions: '18" x 18" [x3] + 12" Sculpted Pumpkin Accent + 50" x 60" Fringed Throw Blanket',
    seatingCapacity: 'Suite of 3 Cushions + 1 Pumpkin Novelty Accent + 1 Fringed Throw',
    colors: ['Oatmeal Natural Tweed', 'Sand Taupe Foliage', 'Crisp Cream Herringbone', 'Ivory Fleece'],
    materials: [
      'Textured Wool-Blend Tweed & Slub Linen',
      'Sculpted Bouclé Fleece Novelty Accent',
      'Woven Herringbone Cotton Throw',
      'Concealed YKK Zippers',
    ],
    badge: 'Nordic Harvest Bestseller',
    isNewArrival: true,
    isTopSelling: true,
    rating: 5.0,
    reviewsCount: 63,
    specifications: {
      frameMaterial: 'Tailored Knife-Edge Seams with Concealed YKK Bottom Zipper',
      foamDensity: '100% Virgin Siliconized Micro-Down Alternative Fiber (650 GSM)',
      suspension: 'Reinforced Overlock Seaming with Anti-Fray Interior',
      warranty: '2 Years Fabric & Seam Burst Guarantee',
      legs: 'Hidden Bottom Zipper Placket',
      customizable: true,
    },
  },
  {
    name: 'myKouch Serene Lake Dusty Blue Jacquard & Velvet Cushion Suite (Set of 4 + Throw Blanket)',
    slug: 'mykouch-serene-lake-dusty-blue-jacquard-cushion-suite',
    description:
      'Calming coastal living elegance. A curated sofa styling ensemble featuring soft dusty blue brushed velvet cushions, intricate silvery-greige woven damask jacquard pillows, and an ultra-soft matching blue fringed knit throw blanket. Tailored with concealed brass zippers and high-loft virgin micro-cluster filling.',
    category: 'Pillow & Cushion',
    subType: 'throw-cushions',
    images: [
      '/assets/pillows/dusty_blue_jacquard_living_cushion_ensemble.jpg',
      '/assets/pillows/designer_living_throw_cushions.jpg',
    ],
    price: 3899,
    originalPrice: 5999,
    discount: 35,
    dimensions: '18" x 18" (45 x 45 cm) [x4] + 50" x 60" Draped Knit Blanket',
    seatingCapacity: 'Suite of 4 Pillows + 1 Matching Fringed Throw Blanket',
    colors: ['Dusty Slate Blue', 'Silvery Greige Jacquard', 'Sand Beige'],
    materials: [
      'Brushed Silk Velvet',
      'Woven Damask Jacquard',
      'Feather-Soft Fringed Acrylic Knit',
      'Concealed YKK Zippers',
    ],
    badge: 'Bestseller Suite',
    isNewArrival: true,
    isTopSelling: true,
    rating: 5.0,
    reviewsCount: 38,
    specifications: {
      frameMaterial: 'Concealed YKK Zipper with Double-Seam Edge Piping & Hand-Tied Tassel Fringe',
      foamDensity: '100% Virgin Siliconized Micro-Down Alternative Fiber (700 GSM)',
      suspension: 'High-Density Interlocking Seam Overlock',
      warranty: '2 Years Seam & Fabric Warranty',
      legs: 'Zipper Base Closure',
      customizable: true,
    },
  },
  {
    name: 'myKouch Tuscany Earth-Tone Velvet & Linen Sectional Cushion Ensemble (Set of 6 + Throw)',
    slug: 'mykouch-tuscany-earth-tone-velvet-sectional-cushion-ensemble',
    description:
      'Designer-coordinated sectional sofa styling package in rich Tuscan warmth. Harmonizes deep wine burgundy crushed velvet, earthy moss olive green, and warm camel tan linen cushion pairs, completed with a plush forest olive knit ottoman throw blanket. Perfectly balanced proportions designed to elevate large L-shaped corner sofas.',
    category: 'Pillow & Cushion',
    subType: 'throw-cushions',
    images: [
      '/assets/pillows/earth_tone_velvet_sectional_cushion_suite.jpg',
      '/assets/pillows/designer_living_throw_cushions.jpg',
    ],
    price: 5499,
    originalPrice: 8499,
    discount: 35,
    dimensions: '20" x 20" (50 x 50 cm) [x2], 18" x 18" [x4] + 50" x 65" Throw Blanket',
    seatingCapacity: '6-Piece Coordinated Sectional Set + 1 Olive Woven Throw',
    colors: ['Deep Burgundy Wine', 'Moss Olive Green', 'Camel Tan Linen'],
    materials: [
      'Heavyweight Royal Velvet',
      'Woven Slub Linen Blend',
      'Textured Ribbed Knit Throw',
      'Hypoallergenic Down Clusters',
    ],
    badge: 'Designer Pick',
    isNewArrival: true,
    isTopSelling: true,
    rating: 4.9,
    reviewsCount: 47,
    specifications: {
      frameMaterial: 'Double-Interlocked Overlock Seams with Hidden Heavy-Duty Zippers',
      foamDensity: 'Dual-Core Micro-Down Alternative Fill with High Resiliency',
      suspension: 'Heavy-Duty Reinforced Stress-Point Stitching',
      warranty: '2 Years Anti-Sag & Seam Warranty',
      legs: 'Hidden Bottom Zipper Placket',
      customizable: true,
    },
  },
  {
    name: 'myKouch Cosy Teddy Bouclé & Chunky Cable-Knit Accent Cushion Trio',
    slug: 'mykouch-cosy-teddy-boucle-chunky-knit-accent-cushion-trio',
    description:
      'Textural warmth for cozy Scandinavian interiors. Handcrafted in ultra-tactile teddy curly bouclé shearling in contrasting cream ivory and rich cocoa mocha, accompanied by a matching heavyweight chunky woven cable-knit fringed throw blanket that drapes effortlessly over sofas and accent armchairs.',
    category: 'Pillow & Cushion',
    subType: 'boucle-accents',
    images: [
      '/assets/pillows/teddy_boucle_chunky_knit_accent_cushions.jpg',
      '/assets/pillows/boucle_sherpa_accent_cushion.jpg',
    ],
    price: 3299,
    originalPrice: 4999,
    discount: 34,
    dimensions: '18" x 18" Bouclé [x2], 12" x 18" Lumbar + 50" x 60" Chunky Throw',
    seatingCapacity: 'Trio of 3 Bouclé Cushions + 1 Chunky Cable-Knit Throw',
    colors: ['Cream Ivory Bouclé', 'Cocoa Mocha Brown', 'Oatmeal Heather Knit'],
    materials: [
      'Tactile Curly Bouclé Fleece',
      'Heavy Chunky Knit Woven Yarn',
      'High-Resilience Poly-Down Fill',
    ],
    badge: 'Trending Cozy',
    isNewArrival: true,
    isTopSelling: true,
    rating: 5.0,
    reviewsCount: 54,
    specifications: {
      frameMaterial: 'Reinforced Concealed Bottom Zipper with Heavy Cable-Knit Edge Finish',
      foamDensity: 'Dense Hypoallergenic Cloud Cushion Core (650 GSM)',
      suspension: 'Chunky Ribbed Edge Binding',
      warranty: '2 Years Texture & Seam Integrity Guarantee',
      legs: 'Zipper Base Closure',
      customizable: true,
    },
  },
  {
    name: 'myKouch Ark Artisan Handwoven Basketweave Lumbar & Textural Cushion Trio',
    slug: 'mykouch-ark-artisan-handwoven-basketweave-lumbar-cushion-trio',
    description:
      'Sculptural artisanal craftsmanship featuring a showstopping handwoven wide basketweave rectangular lumbar pillow in natural flax cotton ribbon. Paired with a deep burgundy crimson velvet square cushion, a textured rustic tweed earthen brown pillow, and a natural cream fringed sofa runner.',
    category: 'Pillow & Cushion',
    subType: 'lumbar-pillows',
    images: [
      '/assets/pillows/handwoven_basketweave_lumbar_textural_cushions.jpg',
      '/assets/pillows/designer_living_throw_cushions.jpg',
    ],
    price: 3699,
    originalPrice: 5499,
    discount: 33,
    dimensions: '14" x 24" Lumbar (Handwoven) + 18" x 18" Squares [x2] + 45" x 70" Fringe Runner',
    seatingCapacity: '1 Handwoven Lumbar + 2 Accent Cushions + 1 Fringed Sofa Runner',
    colors: ['Natural Flax Basketweave', 'Burgundy Crimson', 'Earthen Tweed Brown'],
    materials: [
      '100% Handwoven Cotton Ribbon Tape',
      'Crushed Royal Velvet',
      'Wool-Blend Houndstooth Tweed',
      'Linen Runner with Fringe',
    ],
    badge: 'Artisan Handwoven',
    isNewArrival: true,
    isTopSelling: true,
    rating: 4.9,
    reviewsCount: 29,
    specifications: {
      frameMaterial: 'Interlaced Handwoven Lattice Tape with Concealed Zip Closure',
      foamDensity: 'Firm Ergonomic Lumbar Spine Core + Virgin Microfiber Padding',
      suspension: 'Structural Basketweave Ribbon Webbing',
      warranty: '3 Years Handcraft & Fabric Durability Guarantee',
      legs: 'Concealed Side Zipper',
      customizable: true,
    },
  },
  {
    name: 'myKouch Oasis Botanical Palm & Embroidered Foliage Cushion Suite (Set of 4 + Sage Throw)',
    slug: 'mykouch-oasis-botanical-palm-embroidered-foliage-cushion-suite',
    description:
      'Breathe fresh, revitalizing botanical energy into your living room. Features detailed 3D chain-stitch embroidery depicting a fan palm frond, an olive foliage branch, a geometric four-petal clover motif, and a subtle ladder-stitch framed square, accompanied by an olive sage textured herringbone throw blanket.',
    category: 'Pillow & Cushion',
    subType: 'botanical-cushions',
    images: [
      '/assets/pillows/botanical_palm_embroidered_leaf_cushion_suite.jpg',
      '/assets/pillows/emerald_sofa_cushions_lifestyle.jpg',
    ],
    price: 3999,
    originalPrice: 6299,
    discount: 37,
    dimensions: '18" x 18" (45 x 45 cm) [x4] + 50" x 60" Herringbone Throw',
    seatingCapacity: 'Set of 4 Embroidered Pillows + 1 Sage Herringbone Throw',
    colors: ['Forest Green Embroidery', 'Crisp Canvas Cream', 'Olive Sage Knit'],
    materials: [
      '100% Heavy Cotton Duck Canvas',
      'High-Definition Raised Chain-Stitch Rayon Embroidery Thread',
      'Soft Herringbone Knit Blanket',
    ],
    badge: 'Nature Inspired',
    isNewArrival: true,
    isTopSelling: true,
    rating: 5.0,
    reviewsCount: 65,
    specifications: {
      frameMaterial: 'Raised 3D Botanical Embroidery on Heavy Canvas with Hidden Zipper Placket',
      foamDensity: 'Plush Micro-Cluster Down-Alternative Filling (700 GSM)',
      suspension: 'Precision Double-Needle Boundary Stitching',
      warranty: '2 Years Embroidery & Fabric Guarantee',
      legs: 'Hidden Bottom Zipper Placket',
      customizable: true,
    },
  },
];

const seedTestimonials = [
  {
    customerName: 'Priyanka Mohapatra',
    location: 'Patia, Bhubaneswar',
    sofaPurchased: 'Royal Emerald Velvet L-Shape Sectional',
    review: 'We visited the myKouch showroom near Bhimatangi and were blown away by the quality. They customized the exact 108-inch dimensions to fit our living room corner perfectly! The emerald velvet fabric is super rich and the high-resilience foam feels heavenly.',
    rating: 5,
  },
  {
    customerName: 'Rajesh & Swati Tripathy',
    location: 'Saheed Nagar, Bhubaneswar',
    sofaPurchased: 'Imperial Fluted 3+1+1 Living Room Suite',
    review: 'Direct factory pricing made a huge difference compared to big retail stores. Getting a 10-year solid sal wood frame warranty with custom champagne gold accents for our 3+1+1 set was unmatched. Delivered and installed directly by the myKouch team.',
    rating: 5,
  },
  {
    customerName: 'Abhimanyu Panda',
    location: 'Khandagiri, Bhubaneswar',
    sofaPurchased: 'CloudMotion Motorized Recliner',
    review: 'The motorized recliner is incredible. The mechanism is whisper-quiet and the lumbar support is the best I have ever sat on. It is genuinely handcrafted comfort that feels like home!',
    rating: 5,
  },
  {
    customerName: 'Sunita Dash',
    location: 'Nayapalli, Bhubaneswar',
    sofaPurchased: 'Tuscany Quilted L-Shaped Corner Sofa',
    review: 'From color selection to exact room measurement, the team was patient and professional. The sofa arrived ahead of schedule, beautifully packed and flawless in stitching. Highly recommend myKouch for anyone looking for authentic sofa manufacturing.',
    rating: 5,
  },
];

const seedOffer = {
  title: 'myKouch Festive Living Room Festival 2026',
  subtitle: 'Direct-From-Factory Sofa Event • Handcrafted in Bhubaneswar',
  description: 'Upgrade your living space with customized luxury sofas. Enjoy up to 35% off on all L-shaped sectionals, 3+1+1 living room suites, and motorized recliners. Includes complimentary at-home fabric consultation and custom room measurements.',
  discount: 'UP TO 35% OFF',
  couponCode: 'COMFORT35',
  image: '/assets/sofas/drawing_room_1_2.jpg',
  startDate: new Date(),
  endDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000), // 45 days
  ctaText: 'Explore Sofa Offers',
  ctaLink: '/collections',
  isActive: true,
};

const seedInitialEnquiries = [
  {
    customerName: 'Debabrata Jena',
    phone: '+91 94370 12345',
    email: 'debabrata.jena@gmail.com',
    product: 'myKouch Royal Emerald Velvet L-Shape Sectional',
    enquiryType: 'Customization',
    customizationDetails: {
      sofaType: 'L-Shaped Sofas',
      seatingPreference: '6 Seater with Right Chaise',
      preferredSize: '110" x 70"',
      preferredColor: 'Royal Emerald Teal',
      fabricPreference: 'Royal Velvet (Water-Repellent)',
      roomDimensions: '16 ft x 14 ft Living Room',
      customRequirements: 'Require extra firm lumbar cushion and champagne gold legs.',
    },
    message: 'Hello, I want to confirm if you can deliver and assemble at Sailashree Vihar, Bhubaneswar. Please call me.',
    status: 'New',
  },
  {
    customerName: 'Ananya Pattnaik',
    phone: '+91 98610 88776',
    email: 'ananya.p@outlook.com',
    product: 'myKouch Imperial Fluted 3+1+1 Living Room Suite',
    enquiryType: 'Product Enquiry',
    customizationDetails: {
      sofaType: 'Sofa Combos',
      seatingPreference: '3+1+1',
      preferredColor: 'Ivory Cream',
      fabricPreference: 'Fluted Microfiber',
      roomDimensions: '',
      customRequirements: '',
    },
    message: 'Can I visit the Bhimatangi showroom this Saturday to feel the fabric in person?',
    status: 'Contacted',
    ownerNotes: 'Called customer, confirmed appointment for Saturday 11 AM.',
  },
];

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('[Seed] Connected to MongoDB');

    // 1. Seed Admin
    await Admin.deleteMany({});
    const passwordHash = await Admin.hashPassword('MyKouch@2026');
    const admin = await Admin.create({
      name: 'myKouch Owner',
      email: 'admin@mykouch.in',
      passwordHash,
      role: 'owner',
    });
    console.log(`[Seed] Admin created: ${admin.email} (Password: MyKouch@2026)`);

    // 2. Seed Products
    await Product.deleteMany({});
    const products = await Product.insertMany(seedProducts);
    console.log(`[Seed] ${products.length} sofa products seeded`);

    // 3. Seed Offer
    await Offer.deleteMany({});
    const offer = await Offer.create(seedOffer);
    console.log(`[Seed] Promotional offer seeded: "${offer.title}"`);

    // 4. Seed Testimonials
    await Testimonial.deleteMany({});
    const testimonials = await Testimonial.insertMany(seedTestimonials);
    console.log(`[Seed] ${testimonials.length} testimonials seeded`);

    // 5. Seed Enquiries
    await Enquiry.deleteMany({});
    const enquiries = await Enquiry.insertMany(seedInitialEnquiries);
    console.log(`[Seed] ${enquiries.length} initial enquiries seeded`);

    console.log('[Seed] Database seeding completed successfully!');
    process.exit(0);
  } catch (error) {
    console.error('[Seed Error]:', error);
    process.exit(1);
  }
}

seed();
